name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

#    - name: Updating
#      run: sudo apt-get update
 
    - name: Listing Files 
      run: ls -la

    - name: Build Stage
      run: |
        mvn clean --file my-app/pom.xml
        echo Build started on `date`
        mvn test -f my-app/pom.xml
        ls -la

    - name: Post-Build Stage
      run: |
         echo Build Completed on `date`
         mvn package -f my-app/pom.xml

    - name: Copying JAR file for Deployment
      run: cp my-app/target/*.jar . 

    - name: Final listing
      run: ls -la

#    - name: Connecting to Ec2
#      env: 
#        super_secret: ${{ secrets.EC2 }}
#      run: ssh -i '$secrets.EC2'  ubuntu@13.233.92.41
#        echo '$super_secret'
#       ls -la

    - name: Copying Jar File to remote host
      env: 
        pass: ${{ secrets.DISPLAY }}
      run: |
          sudo apt install ssh-askpass
          echo "$pass" > key.pem
          ls -la
          chmod 400 key.pem
          scp -i key.pem *.jar ubuntu@13.233.92.41:/home/ubuntu/
#          scp -i $pass *.jar ubuntu@13.233.92.41:/home/ubuntu/
#         ls -la
#    - name: ssh deploy
#      uses: easingthemes/ssh-deploy@v2.1.5
#      env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SOURCE: "."
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          TARGET: "/home/ubuntu/"

#    - name: Copy single file to remote
#      uses: garygrossgarten/github-action-scp@release
#      with:
#        local: my-app
#        remote: /home/ubuntu/
#        host: ${{ secrets.REMOTE_HOST }}
#        username: ${{ secrets.REMOTE_USER }}
#        password: ${{ secrets.SSH_PRIVATE_KEY }}
