name: CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Updating
      run: | 
         sudo apt-get update
         java -version
 #   - name: Setting up Environment 
 #     run: |
 #       sudo apt-get install -y openjdk-8-jdk openjdk-8-jre,
 #       sudo install -y maven